In [6]:
import numpy as np
import pandas as pd
import math
import csv
import openpyxl
'''train = np.array([
    [0,0,1,2,3],
    [1,1,2,3,4],
    [2,2,3,4,5],
    [3,3,4,5,6]
]
)'''
'''
train = np.array([
    [0,1,1,1,3],
    [1,1,1,1,4],
    [2,1,1,1,5],
    [3,1,1,1,6]
]
)'''
train = pd.read_csv('train.csv').as_matrix()#read train.csv file
#print(type(train))
#xtrain=train[:,1:4]
#xtrain = xtrain/5
#true_label=train[:,4:5]
#print((xtrain),(true_label))


C:\Users\LN Pandey\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


In [7]:
def encode_into_prob(x,max_val):
    len=x.size
    y_list=[]
    for i in range(len):
        temp=[]
        for j in range(max_val):
            if(x[i]==j):
                temp.append(1)
            else:
                temp.append(0)
            #print(temp)
        y_list.append(temp)
    return y_list
        

In [8]:
xtrain=train[:,1:785]

xmean = np.mean(xtrain , axis=1)
means_expanded = np.outer(xmean, np.ones(784))
#print(means_expanded)
xtrain = xtrain - means_expanded

xstd = np.std(xtrain , axis=1)
std_expanded = np.outer(xstd, np.ones(784))
#print(std_expanded)
xtrain = xtrain*1.0/std_expanded 

true_label = train[:,785:]
y_true=np.array(encode_into_prob(true_label,10))
y_true=y_true.transpose()

#print(type(y_true))
#print(y_true.transpose())
print(xtrain)
print((y_true))

[[-0.55945675 -0.55945675  2.06254185 ...  2.0522595  -0.55945675
  -0.55945675]
 [-0.5380259  -0.5380259  -0.5380259  ... -0.5380259  -0.5380259
  -0.5380259 ]
 [-0.6486501  -0.6486501  -0.6486501  ... -0.6486501  -0.6486501
  -0.6486501 ]
 ...
 [-0.64973918 -0.64973918 -0.64973918 ... -0.64973918 -0.64973918
  -0.64973918]
 [-0.59745866 -0.59745866 -0.59745866 ... -0.59745866 -0.59745866
  -0.59745866]
 [-0.62629522 -0.62629522 -0.62629522 ... -0.62629522 -0.62629522
  -0.62629522]]
[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]


In [9]:
def feedforward(batch_train,hidden_layers):
     
    global weight_matrix_list
    global bias_list
    global preactivation_list 
    preactivation_list=[]
    global activation_list
    activation_list=[]
    global y_hat
    y_hat=[]
    a_new=[]
    a_last_layer=[]
    nos_data = len(batch_train)
    #print(nos_data)
    h=batch_train.transpose()
    preactivation_list.append(h)
    activation_list.append(h)
    #print(h)
    
#     print("y_hat in feed\n",y_hat )
    
    for j in range(hidden_layers):
        
#         print(".............................")
#         print("activation for layer ", j)
#         print(activation_list[j] , activation_list[j].shape)
#         print("weight",j+1)
#         print(weight_matrix_list[j], weight_matrix_list[j].shape)
#         print("bias ",j+1)
#         print(bias_list[j],bias_list[j].shape)
        
        a_new = bias_list[j]+np.matmul(weight_matrix_list[j].transpose(),activation_list[j])
        preactivation_list.append(a_new)
        
#         print("preactivation for layer",j+1)
#         print(preactivation_list[j+1], preactivation_list[j+1].shape)
        
        h = 1.0/(1.0+np.exp(-1*preactivation_list[j+1]))
        activation_list.append(h)

    
    j=hidden_layers
#     print(".............................")
#     print("activation for layer ", j)
#     print(activation_list[j] , activation_list[j].shape)
#     print("weight",j+1)
#     print(weight_matrix_list[j], weight_matrix_list[j].shape)
#     print("bias ",j+1)
#     print(bias_list[j],bias_list[j].shape)
    
    a_last_layer = bias_list[j]+np.matmul(weight_matrix_list[j].transpose(),activation_list[j])
    preactivation_list.append(a_last_layer)
    
#     print("last activation")
#     print(a_last_layer,a_last_layer.shape)

    y_hat = np.array(output(a_last_layer,batch_train))
    y_hat = y_hat.transpose()
    
#     print("y_hat in feedforward")
#     print(y_hat, y_hat.shape)
    
    
def output(a_last_layer,batch_train):
    y_hat_initial=[]
    y_hat_local=[]
    nos_data=len(batch_train)
    for i in range(nos_data):
        y_hat_initial.append(softmax(a_last_layer[:,i:i+1].transpose()))

    length = len(y_hat_initial)
    for i in range(length):
        y_hat_local.append(y_hat_initial[i][0])
    
#     print("y_hat_local", y_hat_local)
#     print("y_hat_initial",y_hat_initial)
    return y_hat_local

def softmax(row_vector):
    sum_all=0
    row_vector = np.exp(row_vector)
    sum_all = np.sum(row_vector , axis=1)         #print("row_vector", row_vector)
    row_vector = (row_vector*1.0/sum_all)         #print("sum_all",sum_all)
    return row_vector

In [10]:
def backpropagation(y_true_batch):
    
#     print("weigt in backpropogation", weight_matrix_list)
#     print("...........y_true_batch..........\n",y_true_batch)
    
    global grad_a_k_list
    grad_a_k_list=[]
    
    global grad_w_k_list
    grad_w_k_list=[]
    
    global grad_h_k_list
    grad_h_k_list=[]
    
    global grad_b_k_list
    grad_b_k_list=[]
    
    global grad_b
    grad_b=[]
    
    global grad_g_dash_a_k_list
    grad_g_dash_a_k_list = []
    
    global grad_a_last
    grad_a_last=[]
    
    k = num_hidden+1
    
#     print("--------------------------in Backpropagation---------------------")
    
    grad_g_dash_a_k_list = g_dash(preactivation_list)
    
#     print("preactivation_list....................")
#     print("Nos. of matrices in preactivation_list is", len(preactivation_list))
#     print(preactivation_list)
#     print("g_dash..................")
#     print("Nos. of matrices in g_dash is ", len(grad_g_dash_a_k_list))
#     print(grad_g_dash_a_k_list)
    
    grad_a_last = -np.subtract(y_true_batch,y_hat)
    
#     print("y_true_batch \n", y_true_batch)
#     print("y_hat \n",y_hat)
    
    grad_a_k_list.insert(0,grad_a_last)
    
#     print("grad_a_last_layer", k)
#     print(grad_a_k_list[0],grad_a_k_list[0].shape)
        
    while(k>0):
        
#         print(".................grad_compute at layer",k)
        
        grad_w_k_list.insert(0,np.matmul(grad_a_k_list[0],preactivation_list[k-1].transpose()))
        
#         print("grad_a", k)
#         print(grad_a_k_list[0],grad_a_k_list[0].shape)
#         print('preactivation  a_',k-1)
#         print(preactivation_list[k-1],preactivation_list[k-1].shape)
#         print("grad_w_",k)
#         print(grad_w_k_list[0],grad_w_k_list[0].shape)
        
        grad_b_k_list.insert(0,grad_a_k_list[0])
        
#         print("grad_b",k)
#         print(grad_b_k_list[0],grad_b_k_list[0].shape)
        
        grad_h_k_list.insert(0,np.matmul(grad_w_k_list[0].transpose(),grad_a_k_list[0]))
        
#         print("grad_w",k)
#         print(grad_w_k_list[0],grad_w_k_list[0].shape)
#         print("grad_a",k)
#         print(grad_a_k_list[0],grad_a_k_list[0].shape)
#         print("grad_h",k-1)
#         print(grad_h_k_list[0],grad_h_k_list[0].shape)
        
        grad_a_k_list.insert(0,np.multiply(grad_h_k_list[0],grad_g_dash_a_k_list[k-1]))
        
#         print("grad_h_k_list[0]",k-1)
#         print(grad_h_k_list[0],grad_h_k_list[0].shape)
#         print("grad_g_dash_a_k_list[k-1]",k-1)
#         print(grad_g_dash_a_k_list[k-1],grad_g_dash_a_k_list[k-1].shape)
#         print("grad_a",k-1)
#         print(grad_a_k_list[0],grad_a_k_list[0].shape)
        k=k-1
#         print("grad_a_ik_list",grad_a_k_list[0])
    
    sum_all_grad_b_of_data(grad_b_k_list)
    

def sum_all_grad_b_of_data(grad_b_k_list):
    length=len(grad_b_k_list)
    i=0
    while(i<length):
        row=[]
        row = np.sum(grad_b_k_list[i],1)
        j = len(row)
        #print(row.shape)
        row = row[:, np.newaxis]
        #print(row.shape , row)
        grad_b.append(row)
        i+=1
    #print("grad_b",grad_b)

def g_dash(preactivation_list):
    length=len(preactivation_list)
    a_modified = preactivation_list[0:length]
    g_dash_a_k_list=[]
    for i in range(length):
        a=(1.0/(1+np.exp(-a_modified[i])))*(1-(1.0/(1+np.exp(-a_modified[i]))))
        g_dash_a_k_list.append(a)
    return g_dash_a_k_list


In [11]:
def decode_yhat_to_classes(y_hat_local):
    col = len(y_hat_local[0])
    max_val=0
    for j in range(col):
        max_val = y_hat_local[0][j]
        index=0
        for i in range(9):
            if(y_hat_local[i+1][j] > max_val):
                y_hat_local[index][j]=0
                index = i+1
                max_val=y_hat[i+1][j]
            else :
                y_hat_local[i+1][j]=0
        y_hat_local[index][j]=1
    return y_hat_local

In [57]:
#ip_neurons = 3 #input layer
ip_neurons = 784
num_hidden = 0
encoding_bits=10
sizes = []
sizes.insert(0,ip_neurons)
sizes.append(encoding_bits)
print(sizes)
print(len(sizes))

weight_matrix_list = []

bias_list =[]
y_hat= []

for i in range(int(num_hidden)+1):
    weight_matrix_list.append(0.01*np.random.rand(sizes[i],sizes[i+1]))
    bias_list.append(0*np.random.rand(sizes[i+1],1))
print(weight_matrix_list)
#print(len(weight_matrix_list))

print(bias_list)
#print(hlist)



[784, 10]
2
[array([[0.00842745, 0.00879241, 0.00240955, ..., 0.00867346, 0.00374577,
        0.0099145 ],
       [0.00154602, 0.00238633, 0.00399281, ..., 0.0076772 , 0.00281038,
        0.00559487],
       [0.00098803, 0.00973544, 0.00837488, ..., 0.00328418, 0.00619729,
        0.00870626],
       ...,
       [0.00039782, 0.0069763 , 0.00365968, ..., 0.00213939, 0.00625135,
        0.00761   ],
       [0.00562398, 0.0003659 , 0.0041835 , ..., 0.00035561, 0.0092253 ,
        0.00751426],
       [0.00176516, 0.00712558, 0.00739367, ..., 0.00836057, 0.0035143 ,
        0.00888762]])]
[array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])]


In [58]:
def momentum_gd(weight_matrix_list,bias_list,xtrain,num_hidden,sizes):
    
    prev_v_w = [] 
    prev_v_b = []
    for i in range(int(num_hidden)+1):
        prev_v_w.append(0*np.random.rand(sizes[i],sizes[i+1]))
        prev_v_b.append(0*np.random.rand(sizes[i+1],1))
    
    v_w = [] 
    v_b =[]
    for i in range(int(num_hidden)+1):
        v_w.append(0*np.random.rand(sizes[i],sizes[i+1]))
        v_b.append(0*np.random.rand(sizes[i+1],1))
        
    len_w = len(weight_matrix_list)  
    len_b = len(bias_list)
    
    eta = 0.001
    batch_size = 10
    num_points_seen = 0
    gamma = 0.4
    epochs = 35
    t=0
    data_length = len(xtrain)
    no_of_batch = int(data_length/batch_size)
    
    for t in range(epochs):
        for batch in range(no_of_batch):
            dw=[]
            db=[]
            for i in range(int(num_hidden)+1):
                dw.append(0*np.random.rand(sizes[i],sizes[i+1]))
                db.append(0*np.random.rand(sizes[i+1],1))
            
            
            for i in range(batch_size):
                l = batch_size*batch + i
                r = batch_size*batch + i + 1
                feedforward(xtrain[l:r,:],num_hidden)
                #print(l , r)
                backpropagation(y_true[:,l:r])

                for j in range(len_w): 
                    dw[j] += grad_w_k_list[j].transpose()
                                    
                for j in range(len_b):
                    db[j] += grad_b[j]
                                
            
            for j in range(len_w): 
                v_w[j] = gamma*prev_v_w[j] + eta*dw[j]
                                    
            for j in range(len_b):
                v_b[j] = gamma*prev_v_b[j] + eta*db[j]
                
            for j in range(len_w):
                weight_matrix_list[j] += -1*v_w[j]
            
            for j in range(len_b):
                bias_list[j] = -1*v_b[j]
                
            for j in range(len_w): 
                prev_v_w[j] = v_w[j]
                                    
            for j in range(len_b):
                prev_v_b[j] = v_b[j]
                
            
        
        print("end of epoch" , t)

In [59]:
momentum_gd(weight_matrix_list,bias_list,xtrain,num_hidden,sizes)
#print(y_hat)

end of epoch 0
end of epoch 1
end of epoch 2
end of epoch 3
end of epoch 4
end of epoch 5
end of epoch 6
end of epoch 7
end of epoch 8
end of epoch 9
end of epoch 10
end of epoch 11
end of epoch 12
end of epoch 13
end of epoch 14
end of epoch 15
end of epoch 16
end of epoch 17
end of epoch 18
end of epoch 19
end of epoch 20
end of epoch 21
end of epoch 22
end of epoch 23
end of epoch 24
end of epoch 25
end of epoch 26
end of epoch 27
end of epoch 28
end of epoch 29
end of epoch 30
end of epoch 31
end of epoch 32
end of epoch 33
end of epoch 34


In [15]:
feedforward(xtrain,num_hidden)
print(y_hat)
y_hat = decode_yhat_to_classes(y_hat)
print(y_hat)

[[1.64986232e-16]
 [6.38675862e-05]
 [6.13861823e-09]
 [7.15616519e-10]
 [1.24159298e-20]
 [1.40912592e-17]
 [9.99906458e-01]
 [9.47444685e-06]
 [6.55901599e-06]
 [1.36342679e-05]]


In [ ]:
def classifcation(y_hat):
    y_predict=[]
    col = len(y_hat[0])
    for j in range(col):
        for i in range(10):
            if(y_hat[i][j]==1):
                y_predict.append(i)
                break
    return np.array(y_predict)
y_predict = classifcation(y_hat)
print((y_predict))
y_predict = y_predict[:, np.newaxis]
print((y_predict))
print(true_label)

In [16]:
def decode_yhat_to_classes(y_hat):
    col = len(y_hat[0])
    max_val=0
    for j in range(col):
        max_val = y_hat[0][j]
        index=0
        for i in range(9):
            if(y_hat[i+1][j] > max_val):
                y_hat[index][j]=0
                index = i+1
                max_val=y_hat[i+1][j]
            else :
                y_hat[i+1][j]=0
        y_hat[index][j]=1
    return y_hat

xtest = pd.read_csv('test.csv').as_matrix()
test=xtest[:,1:]

xmean = np.mean(test , axis=1)
means_expanded = np.outer(xmean, np.ones(784))
#print(means_expanded)
test = test - means_expanded

xstd = np.std(test , axis=1)
std_expanded = np.outer(xstd, np.ones(784))
#print(std_expanded)
test = test*1.0/std_expanded 


feedforward(test,num_hidden)


C:\Users\LN Pandey\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.


In [17]:
print(y_hat)
y_hat = decode_yhat_to_classes(y_hat)
print(y_hat)

[[1.05187311e-14 5.77366058e-06 4.29929625e-04 ... 4.37526007e-14
  4.80713883e-14 4.49936893e-15]
 [6.22146047e-10 1.62808594e-08 8.98580287e-01 ... 1.03597862e-07
  3.44185033e-14 9.99994791e-01]
 [2.67913388e-06 4.03262572e-02 2.83430854e-04 ... 2.57192647e-12
  6.80261103e-11 2.25162677e-13]
 ...
 [3.42187952e-06 2.32486976e-01 2.65746822e-04 ... 7.44347296e-17
  7.37954888e-01 1.90159711e-10]
 [4.10042890e-10 5.89087705e-01 4.64403979e-09 ... 2.24184607e-25
  2.62045083e-01 3.01454119e-19]
 [2.11614101e-07 1.35654591e-13 9.92224358e-02 ... 9.99999891e-01
  2.70496795e-15 8.73197715e-16]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]]


In [18]:
def classifcation(y_hat):
    y_predict=[]
    col = len(y_hat[0])
    for j in range(col):
        for i in range(10):
            if(y_hat[i][j]==1):
                y_predict.append(i)
                break
    return np.array(y_predict)

In [19]:
y_predict = classifcation(y_hat)
print((y_predict))
y_predict = y_predict[:, np.newaxis]
print((y_predict))

[6 8 1 ... 9 7 1]
[[6]
 [8]
 [1]
 ...
 [9]
 [7]
 [1]]


In [20]:
def add_id_to_y_predict(y_predict):
    ide=[]
    row=len(y_predict)
    for i in range(row):
        ide.append(i)
    ide=np.array(ide)
    ide=ide[:,np.newaxis]
    y= np.hstack((ide,y_predict))
    #print(y_predict, ide)
    return y           

In [21]:
print(y_predict)
#y_predict= np.random.randint(10, size=(10000, 1))
y_predict= add_id_to_y_predict(y_predict)
print(y_predict)
x,y = y_predict.shape
#print(x,y)

[[6]
 [8]
 [1]
 ...
 [9]
 [7]
 [1]]
[[   0    6]
 [   1    8]
 [   2    1]
 ...
 [9997    9]
 [9998    7]
 [9999    1]]


In [22]:
with open('predict_from_momentum.csv', 'w', newline='') as f:
    thewriter = csv.writer(f)
    row,col=y_predict.shape 
    thewriter.writerow(['id','label'])
    for i in range(row):
        thewriter.writerow(y_predict[i])
#out.close()
#np.savetxt("foo.csv", y_predict, delimiter=",")

In [54]:
def classifcation(y_hat):
    y_predict=[]
    col = len(y_hat[0])
    for j in range(col):
        for i in range(10):
            if(y_hat[i][j]==1):
                y_predict.append(i)
                break
    return np.array(y_predict)
feedforward(xtrain,num_hidden)
print(y_hat)
y_hat = decode_yhat_to_classes(y_hat)
print(y_hat)

[[2.74224471e-05 8.02264595e-04 1.51039757e-06 ... 5.62434990e-05
  1.79285011e-12 6.22880350e-07]
 [7.62237033e-01 3.12140336e-04 9.98373561e-01 ... 1.98156894e-04
  2.60701929e-08 5.30945066e-03]
 [2.56872572e-06 2.80413107e-03 1.04042595e-03 ... 2.37363219e-04
  1.16089260e-07 1.55871007e-04]
 ...
 [5.04730495e-04 1.81416288e-01 9.88803573e-07 ... 2.04466145e-03
  9.33437547e-15 2.22964139e-03]
 [1.74129178e-07 1.38734604e-03 1.48487543e-08 ... 1.44726347e-07
  1.17193353e-16 1.26111623e-02]
 [5.71122666e-10 2.80570528e-01 2.11814141e-07 ... 2.33313477e-02
  9.99997923e-01 1.98158737e-03]]
[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 1. 0.]]


In [55]:
y_predict = classifcation(y_hat)
print((y_predict))
y_predict = y_predict[:, np.newaxis]
print((y_predict))

[1 9 1 ... 6 9 6]
[[1]
 [9]
 [1]
 ...
 [6]
 [9]
 [6]]


In [56]:
cnt=0
for i in range(55000):
    if(y_predict[i]==true_label[i]):
        cnt+=1
acc = cnt/55000
print(acc)

0.7615454545454545
